# roles/docker/vars/main.yml
---
docker_gpg_url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
docker_repository: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
