- name: Install MySQL client for Debian/Ubuntu
  apt:
    name: "{{ mysql_client_package_debian }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install MySQL client for RedHat/CentOS
  yum:
    name: "{{ mysql_client_package_redhat }}"
    state: present
  when: ansible_os_family == "RedHat"

- name: Install MySQL client for SUSE
  zypper:
    name: "{{ mysql_client_package_suse }}"
    state: present
  when: ansible_os_family == "Suse"
